/**
 * build.js — esbuild bundler for CommonGround frontend
 *
 * MapLibre GL JS is vendored (copied from node_modules) rather than
 * bundled, avoiding web-worker complications and keeping build simple.
 * The app source files are bundled into dist/app.bundle.js.
 *
 * Usage:
 *   node build.js           — production build
 *   node build.js --watch   — rebuild on change
 */
'use strict';
const esbuild = require('esbuild');
const fs = require('fs');
const path = require('path');

const watch = process.argv.includes('--watch');
const isProd = process.env.NODE_ENV === 'production';

// Resolve maplibre dist directory
const maplibrePkg = require.resolve('maplibre-gl/package.json');
const maplibreDir = path.join(path.dirname(maplibrePkg), 'dist');

// Ensure output directories exist
fs.mkdirSync('dist/vendor', { recursive: true });

// Copy MapLibre JS and CSS into dist/vendor (no CDN, fully self-hosted)
fs.copyFileSync(path.join(maplibreDir, 'maplibre-gl.js'), 'dist/vendor/maplibre-gl.js');
fs.copyFileSync(path.join(maplibreDir, 'maplibre-gl.css'), 'dist/vendor/maplibre-gl.css');
console.log('[build] Vendored maplibre-gl.js + maplibre-gl.css');

// ── Generate icon data from @phosphor-icons/core (fill weight) ────────────────
// Maps internal key → Phosphor icon file name (kebab-case, no extension)
// Keys map to Phosphor kebab-case icon names (the -fill.svg suffix is added automatically)
const PHOSPHOR_ICON_MAP = {
  // OSM amenity category icons (used as MapLibre map image sprites)
  community_centre:  'buildings',
  social_facility:   'users-three',
  clinic:            'first-aid',
  health_centre:     'first-aid',
  library:           'books',
  food_bank:         'basket',
  shelter:           'house',
  place_of_worship:  'star',
  park:              'tree-evergreen',
  // Point layer icons
  fqhc:              'stethoscope',
  snap:              'shopping-cart-simple',
  airnow:            'thermometer-simple',
  // Weather condition icons (rendered inline as SVG img tags in weather.js)
  weather_sunny:     'sun',
  weather_partly:    'cloud-sun',
  weather_cloudy:    'cloud',
  weather_rain:      'cloud-rain',
  weather_snow:      'cloud-snow',
  weather_thunder:   'cloud-lightning',
  weather_wind:      'wind',
  weather_night:     'moon-stars',
  weather_fog:       'cloud-fog',
};

(function generatePhosphorIcons() {
  let phosphorDir;
  try {
    // Resolve main entry (dist/index.umd.js), then step up two levels to the package root.
    // We can't use require.resolve('...package.json') because @phosphor-icons/core v2
    // uses an "exports" map that doesn't expose package.json.
    const mainFile = require.resolve('@phosphor-icons/core');
    phosphorDir = path.resolve(path.dirname(mainFile), '..');
  } catch (e) {
    console.warn('[icons] @phosphor-icons/core not found — icons disabled');
    fs.writeFileSync(path.join(__dirname, 'src', '_icons.js'), 'export default {};');
    return;
  }

  const icons = {};
  let found = 0;
  for (const [key, name] of Object.entries(PHOSPHOR_ICON_MAP)) {
    const svgFile = path.join(phosphorDir, 'assets', 'fill', `${name}-fill.svg`);
    if (fs.existsSync(svgFile)) {
      icons[key] = fs.readFileSync(svgFile, 'utf8');
      found++;
    } else {
      console.warn(`[icons] Not found: fill/${name}-fill.svg (key: ${key})`);
      icons[key] = null;
    }
  }

  fs.writeFileSync(
    path.join(__dirname, 'src', '_icons.js'),
    `// Auto-generated by build.js from @phosphor-icons/core — do not edit\n` +
    `export default ${JSON.stringify(icons)};`
  );
  console.log(`[icons] Loaded ${found}/${Object.keys(icons).length} Phosphor fill icons`);
})();

const buildOptions = {
  entryPoints: ['src/app.js'],
  bundle: true,
  outfile: 'dist/app.bundle.js',
  platform: 'browser',
  format: 'iife',
  // maplibregl is loaded as a global from dist/vendor/maplibre-gl.js
  // so we declare it external and tell esbuild its global name
  external: ['maplibre-gl'],
  globalName: 'CG',
  minify: isProd,
  sourcemap: !isProd,
  target: ['es2020', 'chrome90', 'firefox90', 'safari14'],
  define: {
    'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'development'),
  },
};

if (watch) {
  esbuild.context(buildOptions).then(ctx => {
    ctx.watch();
    console.log('[build] Watching for changes...');
  });
} else {
  esbuild.build(buildOptions).then(() => {
    console.log('[build] dist/app.bundle.js — done');
  }).catch(() => process.exit(1));
}
