/**
 * weather.js — weather panel for the sidebar.
 *
 * Fetches current conditions and active NWS alerts from the API /weather
 * endpoint (which proxies to api.weather.gov — no API key required).
 *
 * DESIGN NOTE: weather data is situational context, not a prediction of harm.
 * NWS alert badges are informational; severe-weather + SVI cross-layer alerts
 * (T1-E01) are generated by the alert engine in Phase 2.
 */
'use strict';
import { apiFetch } from './api-client.js';
import ICONS from './_icons.js';

let _map = null;

export async function initWeather(map) {
  _map = map;
  // Fetch NWS forecast and AQI in parallel; AQI doesn't depend on map position
  await Promise.all([refreshWeather(), refreshAqi()]);
}

export async function refreshWeather() {
  if (!_map) return;
  const center = _map.getCenter();
  const lat = center.lat.toFixed(4);
  const lon = center.lng.toFixed(4);

  const currentEl = document.getElementById('weather-current');
  if (currentEl) currentEl.textContent = 'Loading…';

  try {
    const data = await apiFetch(`/weather?lat=${lat}&lon=${lon}`);
    renderWeather(data);
  } catch (err) {
    console.error('[weather] Failed to load weather:', err.message);
    const el = document.getElementById('weather-current');
    if (el) el.textContent = 'Weather unavailable.';
    const badge = document.getElementById('weather-nws-badge');
    if (badge) badge.style.display = 'none';
  }
}

// Fetches the latest AQI from the airnow features layer and renders it in the
// sidebar. Called once on init — AQI data is updated hourly by the ingest scheduler.
export async function refreshAqi() {
  const el = document.getElementById('weather-aqi');
  if (!el) return;

  let geojson;
  try {
    geojson = await apiFetch('/features?layer=airnow');
  } catch (err) {
    console.warn('[weather] AQI unavailable:', err.message);
    el.innerHTML = '<span style="color:var(--text-muted);font-size:9px">AQI unavailable</span>';
    return;
  }

  const features = geojson.features || [];
  if (features.length === 0) {
    el.innerHTML = '<span style="color:var(--text-muted);font-size:9px">AQI data not yet loaded</span>';
    return;
  }

  // Most recent observation by date_time string sort
  const sorted = features.slice().sort((a, b) =>
    (b.properties.date_time || '').localeCompare(a.properties.date_time || '')
  );
  const p = sorted[0].properties;
  const aqi      = p.aqi      ?? '–';
  const category = p.category || 'Unknown';
  const station  = p.station_name || '';
  const param    = p.parameter   || '';
  const color    = aqiColor(p.aqi);

  el.innerHTML = `
    <div class="aqi-row">
      <span class="aqi-label">AQI</span>
      <span class="aqi-value" style="color:${color}">${escHtml(String(aqi))}</span>
      <span class="aqi-category" style="color:${color}">${escHtml(category)}</span>
    </div>
    ${station ? `<div class="aqi-station">${escHtml(station)}${param ? ' · ' + escHtml(param) : ''}</div>` : ''}`;
}

function aqiColor(aqi) {
  const n = parseInt(aqi);
  if (isNaN(n))  return 'var(--text-muted)';
  if (n <= 50)   return '#4CAF50';  // Good
  if (n <= 100)  return '#D4A017';  // Moderate
  if (n <= 150)  return '#FF7E00';  // Unhealthy for Sensitive Groups
  if (n <= 200)  return '#C0392B';  // Unhealthy
  if (n <= 300)  return '#8F3F97';  // Very Unhealthy
  return '#7E0023';                  // Hazardous
}

function renderWeather(data) {
  const currentEl = document.getElementById('weather-current');
  const badgeEl   = document.getElementById('weather-nws-badge');
  if (!currentEl) return;

  // Prefer the first hourly period for current conditions; fall back to daily
  const now     = data.forecast_hourly?.[0];
  const tonight = data.forecast?.[0];
  const period  = now || tonight;

  if (!period) {
    currentEl.textContent = 'No forecast data available.';
    return;
  }

  const temp     = period.temperature ?? '–';
  const unit     = period.temperatureUnit ?? 'F';
  const forecast = period.shortForecast ?? '';
  const wind     = period.windSpeed ?? '';
  const windDir  = period.windDirection ?? '';
  const isDaytime = period.isDaytime !== false;

  const iconEl = makeWeatherIconEl(forecast, isDaytime);
  const iconHtml = iconEl ? iconEl.outerHTML : '';

  currentEl.innerHTML = `
    <div class="weather-row">
      ${iconHtml}
      <span class="weather-temp">${escHtml(String(temp))}°${escHtml(unit)}</span>
      <span class="weather-desc">${escHtml(forecast)}</span>
    </div>
    ${wind ? `<div class="weather-wind">Wind ${escHtml(wind)} ${escHtml(windDir)}</div>` : ''}`;

  // NWS alerts badge
  const nwsAlerts = data.alerts || [];
  if (badgeEl) {
    if (nwsAlerts.length > 0) {
      badgeEl.textContent = `${nwsAlerts.length} NWS ALERT${nwsAlerts.length > 1 ? 'S' : ''}`;
      badgeEl.style.display = '';
      badgeEl.title = nwsAlerts.map(a => escHtml(a.headline || a.event)).join('\n');
    } else {
      badgeEl.style.display = 'none';
    }
  }
}

function escHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

// Map a NWS shortForecast string + isDaytime flag to a Phosphor weather icon key.
function weatherIconKey(forecast, isDaytime) {
  const f = (forecast || '').toLowerCase();
  if (f.includes('thunder') || f.includes('lightning'))  return 'weather_thunder';
  if (f.includes('snow') || f.includes('blizzard'))       return 'weather_snow';
  if (f.includes('sleet') || f.includes('freezing rain')) return 'weather_snow';
  if (f.includes('rain') || f.includes('shower') || f.includes('drizzle')) return 'weather_rain';
  if (f.includes('fog') || f.includes('haze') || f.includes('mist'))       return 'weather_fog';
  if (f.includes('wind') || f.includes('breezy') || f.includes('blustery')) return 'weather_wind';
  if (f.includes('cloud') || f.includes('overcast'))      return 'weather_cloudy';
  if (f.includes('partly') || f.includes('mostly'))       return isDaytime ? 'weather_partly' : 'weather_night';
  if (!isDaytime)                                          return 'weather_night';
  return 'weather_sunny';
}

// Return a 16×16 <img> element using the appropriate Phosphor weather icon.
function makeWeatherIconEl(forecast, isDaytime) {
  const key = weatherIconKey(forecast, isDaytime);
  const svg = ICONS[key];
  if (!svg) return null;
  const color = isDaytime ? '#D4A017' : '#B8A070';
  const colored = svg
    .replace('fill="currentColor"', `fill="${color}"`)
    .replace('<svg ', '<svg width="16" height="16" ');
  const img = document.createElement('img');
  img.src = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(colored);
  img.width = 16;
  img.height = 16;
  img.style.cssText = 'vertical-align:middle;flex-shrink:0';
  img.alt = '';
  return img;
}
